# Generated by Django 3.2.13 on 2022-06-21 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_membership_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
